### ISSUE TITLE
Program crashes with some combination of 3 vowels

### ISSUE THREAD

**Issue by JosuEleder** [neburnodrog/Pyverse#2]
When doing:
```
        verse = Pyverse(palabra)
        rima = verse.consonant_rhyme
```
with some 3-vowel words, the program crashes. Some examples:
esternohioideo
radioautografía
glacioeustatismo

**Comment by rubenkarlsson** [comment]
Hola JosuEleder,

Acabo de descubrir tus issues y me alegro de que le hayas echado un vistazo al programa. Veré si puedo arreglarlo sin demasiado esfuerzo. La verdad es que no me acuerdo para nada de cómo está programado. Además ya no utilizo python en mi día a día. 

Un saludo

**Comment by neburnodrog** [comment]
Hola JosuEleder,

Acabo de descubrir tus issues y me alegro de que le hayas echado un vistazo al programa. Veré si puedo arreglarlo sin demasiado esfuerzo. La verdad es que no me acuerdo para nada de cómo está programado. Además ya no utilizo python en mi día a día.

Un saludo

**Comment by neburnodrog** [comment]
Me vendría bien saber cómo silabizarías esas palabras.

es-ter-no-hioi-de-o?
ra-dioau-to-gra-fí-a? ra-dio-au-to-gra-fí-a? dioau o dio-au?
gla-cioeu-sta-tis-mo? o gla-cio-eu-sta-tis-mo? cioeu o cio-eu? me decanto por la primera. Pero me pregunto como puedo generalizar estos casos tan excepcionales en algun tipo de regla. 

son palabras bien excepcionales y no tengo ni claro cómo pronunciarlas. esterno hioideo? con una pausa?

**Comment by neburnodrog** [comment]
voy a subir una version con lo que yo intuitivamente consideraría correcto en estos casos. Por lo menos el programa no se va a romper con combinaciones de mas de dos vocales.

esternohioideo => es-ter-no-hioi-de-o
glacioeustatismo => gla-cioeus-ta-tis-mo
radioautografía => ra-dioau-to-gra-fí-a

**Comment by JosuEleder** [comment]
¡Genial, muchas gracias!

Estoy de acuerdo con tu silabización, por cierto. Estoy mirando si la RAE
ha dicho algo sobre este tipo de palabras pero no encuentro nada.

Josu

**Comment by neburnodrog** [comment]
Hola de nuevo Josu, 

Recuerdo ahora buscar información sobre estos asuntos en la RAE y no encontrar nada. 
Además, al tomar en consideración el habla natural de los hablantes, cabrían varias interpretaciones, la silabización no es determinista me temo. 

Rubén

**Comment by JosuEleder** [comment]
¡Cierto!

He preguntado a varios amigos lingüistas y coinciden, así que yo estaría
tranquilo con esas decisiones :))

Josu

**Comment by neburnodrog** [comment]
He subido la v1.1.0 a pypi, deberias de poder actualizar el paquete.

un saludo

**Comment by JosuEleder** [comment]
Lo haré cuando llegue a casa, gracias!
